services:
  - type: web
    name: solsphere-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DATABASE_URL
        fromDatabase:
          name: solsphere-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

databases:
  - name: solsphere-db
    databaseName: solsphere
    user: solsphere_user
    plan: free
